name: puzzlehack
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.6.3
  qr_flutter: ^4.0.0
  shortid: ^0.1.1
  provider: ^6.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.0
  go_router: ^3.0.1
  confetti: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
